// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/stok-shell-vibes/ArcticMinimal.tsx": () => import("../components/mockups/stok-shell-vibes/ArcticMinimal.tsx"),
  "./components/mockups/stok-shell-vibes/MidnightOps.tsx": () => import("../components/mockups/stok-shell-vibes/MidnightOps.tsx"),
  "./components/mockups/stok-shell-vibes/WarmEspresso.tsx": () => import("../components/mockups/stok-shell-vibes/WarmEspresso.tsx")
};
